# Generated by Django 4.0.8 on 2022-12-23 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('usuariovistas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
